#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Domain-PublicSuffix
Version  : 0.14.1
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/N/NM/NMELNICK/Domain-PublicSuffix-0.14.1.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/N/NM/NMELNICK/Domain-PublicSuffix-0.14.1.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libd/libdomain-publicsuffix-perl/libdomain-publicsuffix-perl_0.14.1-3.debian.tar.xz
Summary  : 'Parse a domain down to root'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0 MPL-2.0-no-copyleft-exception
Requires: perl-Domain-PublicSuffix-bin
Requires: perl-Domain-PublicSuffix-license
Requires: perl-Domain-PublicSuffix-man
Requires: perl(Class::Accessor::Fast)
Requires: perl(Net::IDN::Encode)
BuildRequires : perl(Class::Accessor::Fast)
BuildRequires : perl(Net::IDN::Encode)

%description
Domain-PublicSuffix
===================
A perl module to parse a domain down to the root TLD utilizing the Mozilla
PublicSuffix file.

%package bin
Summary: bin components for the perl-Domain-PublicSuffix package.
Group: Binaries
Requires: perl-Domain-PublicSuffix-license
Requires: perl-Domain-PublicSuffix-man

%description bin
bin components for the perl-Domain-PublicSuffix package.


%package license
Summary: license components for the perl-Domain-PublicSuffix package.
Group: Default

%description license
license components for the perl-Domain-PublicSuffix package.


%package man
Summary: man components for the perl-Domain-PublicSuffix package.
Group: Default

%description man
man components for the perl-Domain-PublicSuffix package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Domain-PublicSuffix-0.14
mkdir -p %{_topdir}/BUILD/Domain-PublicSuffix-0.14/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Domain-PublicSuffix-0.14/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Domain-PublicSuffix
cp LICENSE %{buildroot}/usr/share/doc/perl-Domain-PublicSuffix/LICENSE
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-Domain-PublicSuffix/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Domain/PublicSuffix.pm
/usr/lib/perl5/site_perl/5.26.1/Domain/PublicSuffix/Default.pm

%files bin
%defattr(-,root,root,-)
/usr/bin/get_root_domain

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Domain-PublicSuffix/LICENSE
/usr/share/doc/perl-Domain-PublicSuffix/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/get_root_domain.1
/usr/share/man/man3/Domain::PublicSuffix.3
/usr/share/man/man3/Domain::PublicSuffix::Default.3
